"""Added Student address

Revision ID: 13b4b1306ef0
Revises: 62a04c729c60
Create Date: 2022-09-14 18:09:03.601918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13b4b1306ef0'
down_revision = '62a04c729c60'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('student_address', sa.String(length=25), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'student_address')
    # ### end Alembic commands ###
